// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProxmoxDashboard.Data;

#nullable disable

namespace ProxmoxDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ProxmoxDashboard.Models.CachedVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Node")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProxmoxServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RAM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VMID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProxmoxServerId");

                    b.ToTable("CachedVMs");
                });

            modelBuilder.Entity("ProxmoxDashboard.Models.ProxmoxServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulFetch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxServers");
                });

            modelBuilder.Entity("ProxmoxDashboard.Models.CachedVM", b =>
                {
                    b.HasOne("ProxmoxDashboard.Models.ProxmoxServer", "ProxmoxServer")
                        .WithMany("CachedVMs")
                        .HasForeignKey("ProxmoxServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxmoxServer");
                });

            modelBuilder.Entity("ProxmoxDashboard.Models.ProxmoxServer", b =>
                {
                    b.Navigation("CachedVMs");
                });
#pragma warning restore 612, 618
        }
    }
}
